name: Continuous Integration
on:
  repository_dispatch:
    types: trigger_build
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  linux_build:
    name: Linux ${{ matrix.config }} build with ${{ matrix.compiler }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: Clang, version: 9,  config: Debug }
          - { compiler: Clang, version: 9,  config: Release }
          - { compiler: GNU,   version: 9,  config: Debug }
          - { compiler: GNU,   version: 9,  config: Release }
          - { compiler: GNU,   version: 10, config: Debug }
          - { compiler: GNU,   version: 10, config: Release }

    steps:
      - name: Setup system
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake lld-9 ninja-build
          if [ ${{matrix.compiler}} = Clang ]
          then
            sudo apt-get install -y clang-${{ matrix.version }}
          elif [ ${{matrix.compiler}} = GNU ]
          then
            sudo apt-get install -y g++-${{ matrix.version }}
          fi
          sudo ln -s /usr/bin/ld.lld-9 /usr/bin/ld.lld

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        run: |
          mkdir build
          cmake \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_C_COMPILER=$([ ${{ matrix.compiler }} = Clang ] && echo clang || echo gcc)-${{ matrix.version }} \
            -DCMAKE_CXX_COMPILER=$([ ${{ matrix.compiler }} = Clang ] && echo clang++ || echo g++)-${{ matrix.version }} \
            -Ddze_functional_sanitize_address=$([ ${{ matrix.config }} = Debug ] && echo ON || echo OFF) \
            -Ddze_functional_sanitize_ub=$([ ${{ matrix.config }} = Debug ] && echo ON || echo OFF) \
            -Ddze_functional_use_lld=ON \
            -B build \
            -S .
          ninja -v -C build

      - name: Benchmark with nanobench
        if: ${{ matrix.config == 'Release' }}
        run: |
          build/benchmark/bench_nanobench

      - name: Benchmark with Google Benchmark
        if: ${{ matrix.config == 'Release' }}
        run: |
          build/benchmark/bench_google_bench
