name: Continuous Integration
on:
  repository_dispatch:
    types: trigger_build
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  linux_build:
    name: Linux ${{ matrix.cfg.config }} build with ${{ matrix.cfg.compiler }} ${{ matrix.cfg.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { compiler: Clang, version: 9,  config: Debug }
          - { compiler: Clang, version: 9,  config: Release }
          - { compiler: GNU,   version: 9,  config: Debug }
          - { compiler: GNU,   version: 9,  config: Release }
          - { compiler: GNU,   version: 10, config: Debug }
          - { compiler: GNU,   version: 10, config: Release }

    steps:
      - name: Setup system
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake lld-9 ninja-build
          if [ ${{matrix.cfg.compiler}} = Clang ]
          then
            sudo apt-get install -y clang-${{ matrix.cfg.version }}
          elif [ ${{matrix.cfg.compiler}} = GNU ]
          then
            sudo apt-get install -y g++-${{ matrix.cfg.version }}
          fi
          sudo ln -s /usr/bin/ld.lld-9 /usr/bin/ld.lld

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        run: |
          mkdir build
          cmake \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.config }} \
            -DCMAKE_C_COMPILER=$([ ${{ matrix.cfg.compiler }} = Clang ] && echo clang || echo gcc)-${{ matrix.cfg.version }} \
            -DCMAKE_CXX_COMPILER=$([ ${{ matrix.cfg.compiler }} = Clang ] && echo clang++ || echo g++)-${{ matrix.cfg.version }} \
            -Ddze_optional_sanitize_address=$([ ${{ matrix.cfg.config }} = Debug ] && echo ON || echo OFF) \
            -Ddze_optional_sanitize_ub=$([ ${{ matrix.cfg.config }} = Debug ] && echo ON || echo OFF) \
            -Ddze_optional_use_lld=ON \
            -B build \
            -S .
          ninja -v -C build

  macos_build:
    name: macOS ${{ matrix.cfg.config }} build with ${{ matrix.cfg.compiler }} ${{ matrix.cfg.version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { compiler: AppleClang, version: x,  config: Debug }
          - { compiler: AppleClang, version: x,  config: Release }
          - { compiler: Clang,      version: 9,  config: Debug }
          - { compiler: Clang,      version: 9,  config: Release }
          - { compiler: Clang,      version: 10, config: Debug }
          - { compiler: Clang,      version: 10, config: Release }
          - { compiler: GNU,        version: 9,  config: Debug }
          - { compiler: GNU,        version: 9,  config: Release }

    steps:
      - name: Setup system
        run: |
          brew install llvm cmake ninja
          if [ ${{matrix.cfg.compiler}} = Clang ]
          then
            brew install llvm@${{ matrix.cfg.version }}
          elif [ ${{matrix.cfg.compiler}} = GNU ]
          then
            brew install gcc@${{ matrix.cfg.version }}
          fi
          sudo ln -s "$(brew --prefix llvm)/bin/clang-tidy" /usr/local/bin/clang-tidy

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        run: |
          mkdir build
          cmake \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.config }} \
            -DCMAKE_C_COMPILER=$( \
              if [ ${{ matrix.cfg.compiler }} = AppleClang ]
              then
                echo clang
              elif [ ${{ matrix.cfg.compiler }} = Clang ]
              then
                echo $(brew --prefix llvm@${{ matrix.cfg.version }})/bin/clang
              elif [ ${{ matrix.cfg.compiler }} = GNU ]
              then
                echo gcc-${{ matrix.cfg.version }}
              fi) \
            -DCMAKE_CXX_COMPILER=$( \
              if [ ${{ matrix.cfg.compiler }} = AppleClang ]
              then
                echo clang++
              elif [ ${{ matrix.cfg.compiler }} = Clang ]
              then
                echo $(brew --prefix llvm@${{ matrix.cfg.version }})/bin/clang++
              elif [ ${{ matrix.cfg.compiler }} = GNU ]
              then
                echo g++-${{ matrix.cfg.version }}
              fi) \
            -Ddze_optional_sanitize_address=$([ ${{ matrix.cfg.config }} = Debug ] && echo ON || echo OFF) \
            -Ddze_optional_sanitize_ub=$([ ${{ matrix.cfg.config }} = Debug ] && echo ON || echo OFF) \
            -B build \
            -S .
          ninja -v -C build

  windows_build:
    name: Windows ${{ matrix.cfg.config }} build with ${{ matrix.cfg.compiler }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { compiler: VS2019, config: Debug }
          - { compiler: VS2019, config: Release }

    steps:
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.2.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # This action downloads ninja to the working directory. Checkout step erases the
      # directory. So this step has to follow checkout.
      - name: Install ninja
        uses: ashutoshvarma/setup-ninja@v1

          #- name: Setup system
          #  shell: bash
          #  run: |
          #    curl -LSso ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip
          #    unzip ninja.zip
          #    echo "::set-env name=PATH::$(pwd):$PATH"

          #- name: Path in bash
          #  shell: bash
          #  run: |
          #    echo $PATH
          #    ninja --version || echo lol

          #- name: Path in ps
          #  run: |
          #    echo $PATH
          #    ninja --version || echo lol

      - name: Build
        shell: bash
        run: |
          mkdir build
          cmake \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.cfg.config }} \
            -DCMAKE_C_COMPILER=cl \
            -DCMAKE_CXX_COMPILER=cl \
            -Ddze_optional_static_analyzer=OFF \
            -B build \
            -S .
          ninja -v -C build
